# Generated by Django 4.2.2 on 2023-06-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='slno',
            field=models.IntegerField(),
        ),
    ]
